/**
 * Error codes for application errors
 * These codes map to translation keys in errors.json
 */

// General errors
export const ERROR_UNKNOWN = 'ERROR_UNKNOWN';
export const ERROR_NETWORK = 'ERROR_NETWORK';
export const ERROR_UNAUTHORIZED = 'ERROR_UNAUTHORIZED';
export const ERROR_NOT_FOUND = 'ERROR_NOT_FOUND';
export const ERROR_SERVER_ERROR = 'ERROR_SERVER_ERROR';

// Validation errors
export const ERROR_VALIDATION_REQUIRED = 'ERROR_VALIDATION_REQUIRED';
export const ERROR_VALIDATION_INVALID_EMAIL = 'ERROR_VALIDATION_INVALID_EMAIL';
export const ERROR_VALIDATION_INVALID_PHONE = 'ERROR_VALIDATION_INVALID_PHONE';
export const ERROR_VALIDATION_INVALID_DATE = 'ERROR_VALIDATION_INVALID_DATE';
export const ERROR_VALIDATION_INVALID_URL = 'ERROR_VALIDATION_INVALID_URL';

// Photo errors
export const ERROR_PHOTO_INVALID_FILE_TYPE = 'ERROR_PHOTO_INVALID_FILE_TYPE';
export const ERROR_PHOTO_FILE_SIZE_EXCEEDED = 'ERROR_PHOTO_FILE_SIZE_EXCEEDED';
export const ERROR_PHOTO_UPLOAD_FAILED = 'ERROR_PHOTO_UPLOAD_FAILED';
export const ERROR_PHOTO_DELETE_FAILED = 'ERROR_PHOTO_DELETE_FAILED';
export const ERROR_PHOTO_LOAD_FAILED = 'ERROR_PHOTO_LOAD_FAILED';
export const ERROR_PHOTO_NOT_FOUND = 'ERROR_PHOTO_NOT_FOUND';
export const ERROR_PHOTO_SET_PRIMARY_FAILED = 'ERROR_PHOTO_SET_PRIMARY_FAILED';

// Tenant errors
export const ERROR_TENANT_NAME_REQUIRED = 'ERROR_TENANT_NAME_REQUIRED';
export const ERROR_TENANT_PROPERTY_REQUIRED = 'ERROR_TENANT_PROPERTY_REQUIRED';
export const ERROR_TENANT_INVALID_EMAIL = 'ERROR_TENANT_INVALID_EMAIL';
export const ERROR_TENANT_INVALID_PHONE = 'ERROR_TENANT_INVALID_PHONE';
export const ERROR_TENANT_CREATE_FAILED = 'ERROR_TENANT_CREATE_FAILED';
export const ERROR_TENANT_UPDATE_FAILED = 'ERROR_TENANT_UPDATE_FAILED';
export const ERROR_TENANT_DELETE_FAILED = 'ERROR_TENANT_DELETE_FAILED';
export const ERROR_TENANT_NOT_FOUND = 'ERROR_TENANT_NOT_FOUND';
export const ERROR_TENANT_INVALID_RESPONSE = 'ERROR_TENANT_INVALID_RESPONSE';
export const ERROR_TENANT_PDF_UPLOAD_FAILED = 'ERROR_TENANT_PDF_UPLOAD_FAILED';
export const ERROR_TENANT_CONTRACT_CREATION_FAILED = 'ERROR_TENANT_CONTRACT_CREATION_FAILED';

// Property errors
export const ERROR_PROPERTY_CREATE_FAILED = 'ERROR_PROPERTY_CREATE_FAILED';
export const ERROR_PROPERTY_UPDATE_FAILED = 'ERROR_PROPERTY_UPDATE_FAILED';
export const ERROR_PROPERTY_DELETE_FAILED = 'ERROR_PROPERTY_DELETE_FAILED';
export const ERROR_PROPERTY_NOT_FOUND = 'ERROR_PROPERTY_NOT_FOUND';
export const ERROR_PROPERTY_INVALID_DATA = 'ERROR_PROPERTY_INVALID_DATA';

// Owner errors
export const ERROR_OWNER_CREATE_FAILED = 'ERROR_OWNER_CREATE_FAILED';
export const ERROR_OWNER_UPDATE_FAILED = 'ERROR_OWNER_UPDATE_FAILED';
export const ERROR_OWNER_DELETE_FAILED = 'ERROR_OWNER_DELETE_FAILED';
export const ERROR_OWNER_NOT_FOUND = 'ERROR_OWNER_NOT_FOUND';

// Contract errors
export const ERROR_CONTRACT_CREATE_FAILED = 'ERROR_CONTRACT_CREATE_FAILED';
export const ERROR_CONTRACT_UPDATE_FAILED = 'ERROR_CONTRACT_UPDATE_FAILED';
export const ERROR_CONTRACT_DELETE_FAILED = 'ERROR_CONTRACT_DELETE_FAILED';
export const ERROR_CONTRACT_NOT_FOUND = 'ERROR_CONTRACT_NOT_FOUND';
export const ERROR_CONTRACT_INVALID_DATES = 'ERROR_CONTRACT_INVALID_DATES';
export const ERROR_CONTRACT_START_DATE_REQUIRED = 'ERROR_CONTRACT_START_DATE_REQUIRED';
export const ERROR_CONTRACT_END_DATE_REQUIRED = 'ERROR_CONTRACT_END_DATE_REQUIRED';
export const ERROR_CONTRACT_END_BEFORE_START = 'ERROR_CONTRACT_END_BEFORE_START';

// Auth errors
export const ERROR_AUTH_LOGIN_FAILED = 'ERROR_AUTH_LOGIN_FAILED';
export const ERROR_AUTH_INVALID_CREDENTIALS = 'ERROR_AUTH_INVALID_CREDENTIALS';
export const ERROR_AUTH_SESSION_EXPIRED = 'ERROR_AUTH_SESSION_EXPIRED';
export const ERROR_AUTH_LOGOUT_FAILED = 'ERROR_AUTH_LOGOUT_FAILED';

/**
 * Custom error class that includes an error code
 */
export class AppError extends Error {
  code: string;

  constructor(code: string, message?: string) {
    super(message || code);
    this.code = code;
    this.name = 'AppError';
  }
}
